reportsapp/urls.py
from django.urls import path, include
from .views import GenreList, CrimeList, CrimeCreate, CrimeDetail, SuspectDetail, VictimDetail, GenerateTextView

urlpatterns = [
    path('genres/', GenreList.as_view(), name='genres'),
    path('genres/<int:genre_id>/crimes/', CrimeList.as_view(), name='crimes'),
    path('crimes/<int:pk>/', CrimeDetail.as_view(), name='crime_detail'),
    path('crimes/<int:pk>/generate', GenerateTextView.as_view(), name='generate'),
    path('genres/<int:genre_id>/crimes/create/', CrimeCreate.as_view(), name="crime_create"),
    path('suspect/', SuspectDetail.as_view(), name='suspect'),
    path('victim/', VictimDetail.as_view(), name='victim')
]

reportsproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("reportsapp.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

reportsapp/models.py
import os
from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.
class GenreModel(models.Model):
    genre_name = models.CharField(max_length=100)

    def __str__(self):
        return self.genre_name


class CrimeModel(models.Model):
    genre = models.ForeignKey(GenreModel, on_delete=models.CASCADE)
    crime_name = models.CharField(max_length=100)
    crime_name_second = models.CharField(max_length=100, null=True, blank=True)
    crime_start_date = models.DateField(null=True, blank=True)
    crime_start_time = models.TimeField(null=True, blank=True)
    crime_end_date = models.DateField(null=True, blank=True)
    crime_end_time = models.TimeField(null=True, blank=True)
    crime_place = models.CharField(max_length=100)
    crime_fact = models.TextField()

    def __str__(self):
        return self.crime_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # モデルの保存処理を先に実行
        content = f"crime name: {self.crime_name}\n"  # ファイルに書き込む内容
        content += f"crime name second: {self.crime_name_second}\n"
        content += f"crime start date: {self.crime_start_date}\n"
        content += f"crime start time: {self.crime_start_time}\n"
        content += f"crime end date: {self.crime_end_date}\n"
        content += f"crime end time: {self.crime_end_time}\n"
        content += f"crime place: {self.crime_place}\n"
        content += f"crime fact: {self.crime_fact}\n"

        # 他のフィールドも同様に追加することができます

        # ファイルのパスを設定
        file_path = os.path.join(settings.BASE_DIR, 'reportsapp', f'crime_{self.pk}.txt')

        # ファイルに内容を書き出し
        with open(file_path, 'w') as file:
            file.write(content)


class SuspectModel(models.Model):
    crime = models.ForeignKey(CrimeModel, on_delete=models.CASCADE)
    honseki = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    job = models.CharField(max_length=100, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name



class VictimModel(models.Model):
    crime = models.ForeignKey(CrimeModel, on_delete=models.CASCADE)
    address = models.CharField(max_length=100, null=True, blank=True)
    job = models.CharField(max_length=100, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

reportsapp/forms.py
from django import forms

class UserInputForm(forms.Form):
    user_text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'テキストを入力'}), label='')

reportsapp/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from .models import GenreModel, CrimeModel, SuspectModel, VictimModel
from django.urls import reverse_lazy
from .services import generate_text
from .forms import TextInputForm
from django.views.generic.edit import FormView
from django.urls import reverse_lazy




# Create your views here.
class GenreList(ListView):
    model = GenreModel
    template_name = 'genre_list.html'

class CrimeList(ListView):
    model = CrimeModel
    template_name = 'crime_list.html'

    def get_queryset(self):
        return CrimeModel.objects.filter(genre_id=self.kwargs['genre_id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre_id'] = self.kwargs['genre_id']
        return context

class CrimeDetail(DetailView):
    model = CrimeModel
    template_name = 'crime_detail.html'

    def get_queryset(self):
        """関連する容疑者と被害者の情報も取得する。"""
        return CrimeModel.objects.prefetch_related('suspectmodel_set', 'victimmodel_set')

class CrimeCreate(CreateView):
    model = CrimeModel
    fields = ['crime_name', 'crime_name_second', 'crime_start_date', 'crime_start_time', 'crime_end_date', 'crime_end_time', 'crime_place', 'crime_fact']
    template_name = 'crime_create.html'
    # success_url = reverse_lazy('crime')
    
    def form_valid(self, form):
        form.instance.genre_id = self.kwargs['genre_id']
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('crimes', kwargs={'genre_id': self.kwargs['genre_id']})

class SuspectDetail(DetailView):
    model = SuspectModel
    template_name = 'suspect_detail.html'

class VictimDetail(DetailView):
    model = VictimModel
    template_name = 'victim_detail.html'


from .forms import TextInputForm
from .utils import process_text

class GenerateTextView(FormView):
    template_name = 'generate.html'
    form_class = TextInputForm
    success_url = reverse_lazy('generate')  # 'generate'はこのビューを指すURLのname属性

    def form_valid(self, form):
        # フォームのデータが有効な場合に呼ばれる
        user_text = form.cleaned_data['user_text']
        processed_text = process_text(user_text)
        # 処理結果をテンプレートに渡す
        return self.render_to_response(self.get_context_data(processed_text=processed_text))

templates/crime_create.html
{% comment %} {% load static tailwind_tags %} {% endcomment %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>事件管理</title>

    {% comment %} {% tailwind_css %} {% endcomment %}

</head>
<body class="bg-indigo-950 text-white">

    {% block header %}
    <h1 class="text-3xl py-5 px-6 border-b-2 border-gray-400 bg-green-700">事件管理</h1>
    {% endblock header %}

    <div class="container py-5 px-auto m-auto">
    {% block content %}

    <h2>新規作成</h2>
    <form method="post">{% csrf_token %}
    {% comment %} {{ form.as_p }}  <!-- フォームをパラグラフタグで表示 --> {% endcomment %}
    <div class="flex items-center mt-8">
        <label for="crime_name" class="mr-3">罪名</label>
        <input type="text" name="crime_name" id="crime_name" class="mr-8">
        <label for="crime_name_second" class="mr-3">中種別</label>
        <input type="text" name="crime_name_second" id="crime_name_second">
    </div>
    <div class="">
        <label for="crime_start_date">発生日時</label>
        発生日<input type="date" name="crime_start_date" id="crime_start_date">
        発生時間<input type="time" name="crim_start_time" id="crim_start_time"> ~
        発生日<input type="date" name="crime_end_date" id="crime_end_date">
        発生時間<input type="time" name="crime_end_time" id="time">
    </div>
    <div class="">
        <label for="crime_place">発生場所</label>
        <input type="text" name="crime_place" id="crime_place" class="w-4/5">
    </div>
    <div class="">
        <label for="crime_fact">概要</label>
        <textarea name="crime_fact" id="crime_fact" cols="30" rows="10"></textarea>
    </div>
    <button type="submit" class="py-2 px-5 text-teal-400 border-2 border-green-500 rounded hover:opacity-70">Save</button>
    </form>

    {% endblock content %}

    <form action="">
        <p>被疑者</p>
        <div class="">
            <label for="honseki">本籍</label>
            <input type="text" name="honseki" id="honseki">
        </div>
        <div class="">
            <label for="address">住居</label>
            <input type="text" name="address" id="address">
        </div>
        <div class="">
            <label for="job">職業</label>
            <input type="text" name="job" id="job">
        </div>
        <div class="">
            <label for="name">氏名</label>
            <input type="text" name="name" id="name">
        </div>
        <div class="">
            <label for="birthday">生年月日</label>
            <input type="text" name="birthday" id="birthday">
        </div>
    </form>


    <form action="">
        <p>被害者</p>
        <div class="">
            <label for="address">住居</label>
            <input type="text" name="address" id="address">
        </div>
        <div class="">
            <label for="job">職業</label>
            <input type="text" name="job" id="job">
        </div>
        <div class="">
            <label for="name">氏名</label>
            <input type="text" name="name" id="name">
        </div>
        <div class="">
            <label for="birthday">生年月日</label>
            <input type="text" name="birthday" id="birthday">
        </div>
    </form>



</body>
</html>

templates/crime_detail.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>事件管理</title>

    {% tailwind_css %}

</head>
<body class="bg-indigo-950 text-white">

    {% block header %}
    <h1 class="text-3xl py-5 px-6 border-b-2 border-gray-400 bg-green-700">事件詳細</h1>
    {% endblock header %}

    <div class="container py-5 px-auto m-auto">
    {% block content %}

    <a href="{% url 'generate' pk=object.pk %}" class="py-2 px-5 text-teal-400 border-2 border-green-500 rounded hover:opacity-70">自動生成</a>
    <div class="mt-8">
        <h2>罪名：{{ object.crime_name }}（{{ object.crime_name_second }}）</h2>
        <p>発生日時: {{ object.crime_datetime|date:"Y-m-d H:i" }}</p>
        <p>発生場所: {{ object.crime_place }}</p>
        <p>犯罪の概要: {{ object.crime_fact }}</p>
        <h3 class="mt-9">被疑者の情報:</h3>
        {% for suspect in object.suspectmodel_set.all %}
            <div>
                <p>名前: {{ suspect.name }}</p>
                <p>本籍地: {{ suspect.honseki }}</p>
                <p>住所: {{ suspect.address }}</p>
                <p>職業: {{ suspect.job }}</p>
                <p>誕生日: {{ suspect.birthday|date:"Y-m-d" }}</p>
            </div>
        {% endfor %}
        <h3 class="mt-9">被害者の情報:</h3>
        {% for victim in object.victimmodel_set.all %}
            <div>
                <p>名前: {{ victim.name }}</p>
                <p>住所: {{ victim.address }}</p>
                <p>職業: {{ victim.job }}</p>
                <p>誕生日: {{ victim.birthday|date:"Y-m-d" }}</p>
            </div>
        {% endfor %}
    </div>

    {% endblock content %}

    </div>
</body>
</html>

templates/crime_list.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>事件管理</title>

    {% tailwind_css %}

</head>
<body class="bg-indigo-950 text-white">

    {% comment %} {% block header %}
    <h1 class="text-3xl py-5 px-6 border-b-2 border-gray-400 bg-green-700">{{ genre_name }}　|　事件リスト</h1>
    {% endblock header %} {% endcomment %}

    <div class="container py-5 px-auto m-auto">
    {% block content %}
    {% comment %} {% for genre in object_list %} {% endcomment %}
    <a href="{% url 'crime_create' genre_id=genre_id %}" class="py-2 px-5 text-teal-400 border-2 border-green-500 rounded hover:opacity-70">新規作成</a>
    {% comment %} {% endfor %} {% endcomment %}

            {% for crime in object_list %}
            {% comment %} {% for suspect in crime.suspectmodel_set.all %} {% endcomment %}
            {% comment %} {% for victim in crime.victimmodel_set.all %} {% endcomment %}
            <a href="{% url 'crime_detail' pk=crime.pk %}" class="block text-center mt-5 text-xl hover:opacity-70 border-2 border-gray-400 py-4 px-5">
                <div class="flex justify-start items-center mb-3">
                    <p class="mr-6">{{ crime.crime_name }}（{{ crime.crime_name_second }}）</p>
                    <p class="text-sm mr-12">発生日時：{{ crime.crime_start_datetime }} ~ {{ crime.crime_end_datetime }}</p>
                    <p class="text-sm">発生場所：{{ crime.crime_place }}</p>
                </div>
                <div class="flex justify-start">
                    {% comment %} <p class="text-sm mr-10">被疑者：{{ suspect.name }}</p> {% endcomment %}
                    {% comment %} <p class="text-sm">被害者：{{ victim.name }}</p> {% endcomment %}
                </div>
            </a>
            {% comment %} {% endfor %} {% endcomment %}
            {% comment %} {% endfor %} {% endcomment %}
            {% endfor %}
    {% endblock content %}

    </div>
</body>
</html>

templates/generate.html
<!-- templates/generate.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>テキスト生成</title>
</head>
<body>
    <h1>テキストを入力してください</h1>
    <form method="post">
        {% csrf_token %}
        <label for="id_user_text">テキストを入力してください</label>
        <input type="text" name="user_text" id="id_user_text" placeholder="ここにテキストを入力" value="{{ form.user_text.value|default_if_none:'' }}" />
        <button type="submit">送信</button>
    </form>

    {% if processed_text %}
        <h2>処理結果</h2>
        <p>{{ processed_text }}</p>
    {% endif %}
</body>
</html>

templates/genre_list.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>事件管理</title>

    {% tailwind_css %}

</head>
<body class="bg-indigo-950 text-white">

    {% block header %}
    <h1 class="text-3xl py-5 px-6 border-b-2 border-gray-400 bg-green-700">事件管理</h1>
    {% endblock header %}

    <div class="container py-5 px-auto m-auto">
    {% block content %}
            {% for genre in object_list %}
            <a href="{% url 'crimes' genre_id=genre.pk %}" class="block text-center mt-5 text-2xl hover:opacity-70">{{ genre.genre_name }}</a>
            {% endfor %}
    {% endblock content %}

    </div>
</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>